### ISSUE TITLE
Cogent not installing with tox

### ISSUE THREAD

**Issue by mbiokyle29** [pycogent/pycogent#93]
I use cogent in a project I am developing, but it is crashing when I run tox. It can't seem to find numpy even though it is installed. Here is some relevant information:

Here is my setup.py file:
```python
from setuptools import setup, find_packages

setup(
    name='###########',
    version='0.0.1',
    packages=find_packages(exclude=['*test*']),
    install_requires=['potion-client', 'requests==2.9'],
    include_package_data = True,
    zip_safe = False,
    extras_require={
        'all': ['colored', 'numpy', 'pandas', 'cogent']
    },
    setup_requires=[],
    tests_require=['nose', 'flake8', 'tox', 'colored', 'httmock', 'numpy', 'pandas', 'cogent'],
    author='Kyle McChesney',
    author_email='###############',
    description='',
    license='Apache License Version 2.0',
    keywords='###############',
    url='TBD',
    classifiers=[],
    test_suite='nose.collector'
)
```
And here is my tox config file:
```ini
[tox]
envlist = py27,py30,py340

[testenv]
commands = python setup.py test
```
When I run `python setup.py test` outside of tox it works, but when I run tox it fails (for all three envs) with the following message:
```
GLOB sdist-make: /home/kyle/Dev/mycompany/mycompany-client/setup.py
py27 create: /home/kyle/Dev/mycompany/mycompany-client/.tox/py27
py27 inst: /home/kyle/Dev/mycompany/mycompany-client/.tox/dist/mycompany-0.0.1.zip
py27 installed: You are using pip version 8.0.0, however version 8.0.2 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.,functools32==3.2.3.post2,jsonschema==2.5.1,mycompany==0.0.1,Potion-client==0.1.1,requests==2.9.0,six==1.10.0,wheel==0.26.0
py27 runtests: PYTHONHASHSEED='1343403498'
py27 runtests: commands[0] | python setup.py test
running test
Searching for cogent
Reading https://pypi.python.org/simple/cogent/
Best match: cogent 1.5.3
Downloading https://pypi.python.org/packages/source/c/cogent/cogent-1.5.3.tgz#md5=ecdfa0bc89e0c04c9d4d39cac9984498
Processing cogent-1.5.3.tgz
Writing /tmp/easy_install-qZxKNC/cogent-1.5.3/setup.cfg
Running cogent-1.5.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qZxKNC/cogent-1.5.3/egg-dist-tmp-KoeFJL
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    test_suite='nose.collector'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/test.py", line 152, in run
    self.distribution.fetch_build_eggs(self.distribution.tests_require)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1072, in best_match
    return self.obtain(req, installer)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1084, in obtain
    return installer(requirement)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 640, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 670, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 853, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1081, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1067, in run_setup
    run_setup(setup_script, args)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 242, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 239, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 269, in run
    return func()
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 238, in runner
    _execfile(setup_script, ns)
  File "/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-qZxKNC/cogent-1.5.3/setup.py", line 25, in <module>
    
RuntimeError: Numpy required but not found.
ERROR: InvocationError: '/home/kyle/Dev/mycompany/mycompany-client/.tox/py27/bin/python setup.py test'
```
Any ideas here? I tried having tox explicitly install everything like this:
```ini
# original tox ini file - using requirements
[tox]
envlist = py27,py30,py340

[testenv]
deps = -rrequirements.txt
commands = python setup.py test
```
But that hangs for about 3 mins and then fails with:
```
ERROR: invocation failed (exit code 1), logfile: /home/kyle/Dev/my-company/my-company-client/.tox/py27/log/py27-1.log
ERROR: actionid: py27
msg: getenv
cmdargs: [local('/home/kyle/Dev/my-company/my-company-client/.tox/py27/bin/pip'), 'install', '-rrequirements.txt']
##
## Appended
##
Collecting numpy (from -r requirements.txt (line 7))
  Using cached numpy-1.10.4.tar.gz
Collecting pandas (from -r requirements.txt (line 8))
  Using cached pandas-0.17.1.tar.gz
Collecting cogent (from -r requirements.txt (line 9))
/home/kyle/Dev/my-company/my-company-client/.tox/py27/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached cogent-1.5.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zqYDwT/cogent/setup.py", line 25, in <module>
        raise RuntimeError("Numpy required but not found.")
    RuntimeError: Numpy required but not found.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zqYDwT/cogent
You are using pip version 8.0.0, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

ERROR: could not install deps [-rrequirements.txt]; v = InvocationError('/home/kyle/Dev/my-company/my-company-client/.tox/py27/bin/pip install -rrequirements.txt (see /home/kyle/Dev/my-company/my-company-client/.tox/py27/log/py27-1.log)', 1)
```

I don't think its the `InsecurePlatformWarning`. Any ideas?

**Comment by GavinHuttley** [comment]
The pip support in PyCogent is flaky -- sorry -- in that it really does require numpy to be installed prior to running pip! To confirm that's the issue, can you edit your setup.py script so it's only dependencies are cogent and numpy. Then see if the above issue persists.

Also, the released version of PyCogent on PyPi is very out of date. I recommend modifying your script (after addressing the above) to reference the development version, e.g.
```python
    install_requires=[
              'numpy',
              'cogent==1.5.3-dev',
          ],

```
and include a corresponding dependency link
```python
dependency_links=['https://github.com/GavinHuttley/pycogent/archive/master.zip#egg=cogent-1.5.3-dev'],
```

**Comment by mbiokyle29** [comment]
Hey Gavin,

Thanks for getting back to me on this. I have updated my setup.py to use the github version of cogent. I also have a work around for getting tox to work. I specify numpy as a dependency, and then run setup.py, which pulls in all other deps (cogent)

```ini
# new tox ini file
[tox]
envlist = py27,py340

[testenv]
deps = numpy
commands = python setup.py test

[flake8]
exclude = onecodex/schemas/*
```

Thanks for your help!
